const { tz_parseTimeParam } = require('../features/timezones.js');

describe('Testing timezone.js : tz_parseTimeParam : typeA_all format',() => {
  let result
  it ('recognises common typeA_all inputs', () => {
    result = tz_parseTimeParam("-3h15m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_all")
    expect(result.hour).toBe("-3")
    expect(result.minute).toBe("15")
    result = tz_parseTimeParam("4h7m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_all")
    result = tz_parseTimeParam("-8h30m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_all")
  })

  it ('recognises uncommon typeA_all inputs', () => {
    result = tz_parseTimeParam("00h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
    result = tz_parseTimeParam("0h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
    result = tz_parseTimeParam("-0h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
  })
  it ('rejects invalid format typeA_all inputs', () => {
    result = tz_parseTimeParam("375h8m")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("-30000024h8m")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
  it ('rejects invalid characters typeA_all inputs', () => {
    result = tz_parseTimeParam("foobar")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("Hello World!!!")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("!@#$%^&*()_&^%$")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})

describe('Testing timezone.js : tz_parseTimeParam : typeA_hours format',() => {
  let result
  it ('recognises common typeA_hours inputs', () => {
    result = tz_parseTimeParam("-7h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
  })
  it ('recognises uncommon typeA_hours inputs', () => {
    result = tz_parseTimeParam("00h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
    result = tz_parseTimeParam("0h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
    result = tz_parseTimeParam("-0h")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_hours")
  })

  it ('rejects uncommon typeA_hours inputs', () => {
    result = tz_parseTimeParam("--9h")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})


describe('Testing timezone.js : tz_parseTimeParam : typeA_minutes format',() => {
  let result
  it ('recognises common typeA_minutes inputs', () => {
    result = tz_parseTimeParam("1m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")
    result = tz_parseTimeParam("45m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")
    result = tz_parseTimeParam("-30m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")

  })
  it ('recognises uncommon typeA_minutes inputs', () => {
    result = tz_parseTimeParam("60m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")
    result = tz_parseTimeParam("-0m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")
    result = tz_parseTimeParam("70m")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeA_minutes")
  })
  it ('rejects invalid typeA_minutes inputs', () => {

    result = tz_parseTimeParam("700m")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("-600m")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("words")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})

describe('Testing timezone.js : tz_parseTimeParam : typeB_all format',() => {
  let result
  it ('recognises common typeB_all inputs', () => {
    result = tz_parseTimeParam("12:15am")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_all")
    result = tz_parseTimeParam("7:45pm")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_all")
    result = tz_parseTimeParam("1:00pm")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_all")
  })
  it ('rejects invalid typeB_all inputs', () => {
    result = tz_parseTimeParam("09:27am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("00:15am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("13:00am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("11:77pm")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("-9:00pm")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})

describe('Testing timezone.js : tz_parseTimeParam : typeB_hours format',() => {
  let result
  it ('recognises common typeB_hours inputs', () => {
    result = tz_parseTimeParam("9am")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_hours")
    result = tz_parseTimeParam("12pm")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_hours")
    result = tz_parseTimeParam("6pm")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeB_hours")
  })
  it ('rejects invalid typeB_hours inputs', () => {
    result = tz_parseTimeParam("09:27am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("13am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("01am")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("-4pm")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("77pm")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})

describe('Testing timezone.js : tz_parseTimeParam : typeC_all format',() => {
  let result
  it ('recognises common typeC_all inputs', () => {
    result = tz_parseTimeParam("0927")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("1342")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("2000")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("1717")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
  })
  it ('recognises uncommon typeC_all inputs', () => {
    result = tz_parseTimeParam("0001")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("0000")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("2359")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
    result = tz_parseTimeParam("2400")
    expect(result.valid).toBe(true)
    expect(result.type).toBe("typeC_all")
  })
  it ('rejects invalid typeC_all inputs', () => {
    result = tz_parseTimeParam("2700")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("2269")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
    result = tz_parseTimeParam("0160")
    expect(result.valid).toBe(false)
    expect(result.type).toBe("invalid")
  })
})